apiVersion: v1
kind: ServiceAccount
metadata:
  name: cr-greetings-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cr-greetings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cr-greetings
  template:
    metadata:
      labels:
        app: cr-greetings
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "false"
    spec:
      containers:
      - name: cr-greetings
        image: public.ecr.aws/l7i6h0r0/echo-eks-go:latest
        ports:
          - containerPort: 8080
            name: http
        env:
          - name: MESSAGE
            # value: "https://my-api-spring-n7akaif65q-uc.a.run.app"
            value: "I'm running on cloud run"
      serviceAccountName: cr-greetings-service
---
apiVersion: v1
kind: Service
metadata:
  name: "cr-greetings-service"
  labels:
    app: "cr-greetings"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: "cr-greetings"
  type: "LoadBalancer"