global:
  enabled: false
  name: consul
  enableConsulNamespaces: true
  cloud:
    resourceId:
      secretName: consul-hcp-resource-id
      secretKey: resource-id
  metrics:
    enableTelemetryCollector: true
  datacenter: consul-cluster-1-16
  image: "hashicorp/consul-enterprise:1.16.3-ent"
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  tls:
    enabled: true
  enableConsulNamespaces: true
externalServers:
  enabled: true
  hosts: [""]
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: 
server:
  enabled: false
connectInject:
  enabled: true
  logLevel: "trace"
  consulNamespaces: 
    consulDestinationNamespace: default
controller:
  enabled: true
terminatingGateways:
  enabled: true
telemetryCollector:
  enabled: true
  cloud:
    clientId:
      secretKey: client-id
      secretName: consul-hcp-client-id
    clientSecret:
      secretKey: client-secret
      secretName: consul-hcp-client-secret
  logLevel: "trace"